# program 4 makefile
# burrou5
# Cameron L. Burroughs
# Compiler flags

CFLAGS  = -Wall
CC = gcc

#target executable:
TARGET = paging

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	rm  $(TARGET)
